esphome:
  name: environment-monitor--garage
  friendly_name: Environment Monitor - Garage

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "PDuSfuxAXHeaIEyZ02hwWAXwEHO+h5C59/oT8sp2Cv8="

ota:
  password: "12dfd256ce9c4922bfc22bdb878c21a7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Environment-Monitor--Garge"
    password: "FAokleTeMMHD"

captive_portal:
    